### ISSUE TITLE
Please add a license, readme & screen shot

### ISSUE THREAD

**Issue by unixorn** [lorond/zsh-custom#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with a readme that includes a screen shot so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally, please consider renaming the repository to something less generic.

Thanks!

**Comment by lorond** [comment]
@unixorn renamed repo to zsh-lorond
